import './globals.css';
import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';

const ubuntu = Ubuntu({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Multi-step form',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
